### ISSUE TITLE
Expose Blob Properties

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/AzureStorageTypeProvider#102]
It would be useful to be able to retrieve the blob's properties in a more F#-natural way. Currently you need to do the following: -

```fsharp
let cloudBlockBlob = blob.AsCloudBlockBlob() // first convert to standard Azure SDK
do! cloudBlockBlob.FetchAttributesAsync() |> Async.AwaitTask // side-effectful update of the Properties property ...
let blobTimestamp = cloudBlockBlob.Properties.LastModified // now it's "safe" to get the properties
```
etc. etc.

We should expose the properties object as an async method on the BlobFile e.g.

```fsharp
async {
    let properties = blob.GetProperties((* optional connection string goes here... *))
    return properties.LastModified
}
```
An optional (preferred) enhancement would be to create a dedicated F# type for the properties rather than the standard .NET one so that you don't see `Nullable` but rather `Option` etc.

**Comment by alex-bogomaz** [comment]
hello. 2 questions here:
1. should there be similar GetProperties method for blob containers? For consistency.  Example:
```fsharp
member __.GetProperties(?connectionString) = async {
        let containerRef = getBlobContainerRef connectionString
        do! containerRef.FetchAttributesAsync() |> Async.AwaitTask
        return BlobContainerMetadata containerRef.Properties } //returns wrapped BlobContainerProperties object
```
If yes - I can create PR.

2. there are number BlobProperties properties that are not exposed in BlobMetadata: AppendBlobCommittedBlockCount, LeaseDuration, LeaseState, LeaseStatus, PageBlobSequenceNumber. What is the reason?

**Comment by isaacabraham** [comment]
@alex-bogomaz hey.

1. Yes please re: PR for Container properties.
2. Doh - simply forgot them! Feel free to add a PR to add them in too :-)
