### ISSUE TITLE
Allow account details to be loaded via a file

### ISSUE THREAD

**Issue by TWith2Sugars** [fsprojects/AzureStorageTypeProvider#31]
I prefer not to commit account details in to source control but with the provider as it currently stands I have no other choice.

Would be good if I could pass a file location which contain those details.

**Comment by isaacabraham** [comment]
@dsyme is it worth us implementing something for this here - or do you know if there's any work anyone is planning to do with ProvidedTypes.fs to give this sort of functionality OOTB?

**Comment by isaacabraham** [comment]
Closed from #62.
