### ISSUE TITLE
Remove reliance on Azure .NET SDK

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/AzureStorageTypeProvider#32]
The Azure .NET SDK is large (adding over 1mb to the nuget package) and contains lots of fluff that is not needed.
Currently the TP only uses a relatively small proportion of the SDK so should look to hand-roll a thin wrapper around the raw REST API.

**Comment by isaacabraham** [comment]
Related to #55.

**Comment by isaacabraham** [comment]
I'm not sure if this is desirable any longer - the "fallback" methods on the provided types are sometimes quite useful.

**Comment by stewart-r** [comment]
FWIW I'd also agree with that view - in my own opinion we get enough value to warrant the extra baggage. The ability to fallback to the SDK types is useful. Leaning on the SDK also makes it a little easier to write new functionality
