### ISSUE TITLE
Move to fsprojects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/AzureStorageTypeProvider#49]
Hi @isaacabraham 

Would you be interested in moving this to http://github.com/fsprojects?  I don't mind either way but moving can raise visibility and a few other benefits like that.

thanks!
don

**Comment by isaacabraham** [comment]
Yes, sure - what's the process that I should follow to move it in there?

**Comment by dsyme** [comment]
You are now an owner on https://github.com/orgs/fsprojects-transfer/, please transfer the repo to that organization.  @sergey-tihon or the @fsgit account will then complete the transfer and set you up with full admin rights on the repo.  GitHub should look after forwarding the links to the repo automagically.

**Comment by dsyme** [comment]
Done!

**Comment by isaacabraham** [comment]
:)

**Comment by sergey-tihon** [comment]
@isaacabraham Congrats!
The next step is [to share ownership of NuGet package](https://github.com/fsprojects/FsProjectsAdmin/issues/6)?

**Comment by isaacabraham** [comment]
Done

**Comment by sergey-tihon** [comment]
Thank you
