### ISSUE TITLE
Why does downloadFolder call Async.Start?

### ISSUE THREAD

**Issue by ahmelsayed** [fsprojects/AzureStorageTypeProvider#58]
I don't think that [`downloadFolder`](https://github.com/fsprojects/AzureStorageTypeProvider/blob/master/src/FSharp.Azure.StorageTypeProvider/Blob/BlobRepository.fs#L74) should be calling `Async.Start`. I would think that it should just return the `Async<unit>` so that the caller of `Download(path)` can await it.

**Comment by isaacabraham** [comment]
You could be right - it was originally used within scripts where it just seemed to be easier to use if it didn't need to be awaited. Happy to accept a PR that changes this.

**Comment by ahmelsayed** [comment]
Thanks @isaacabraham I opened #59
