### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by stewart-r** [fsprojects/AzureStorageTypeProvider#77]
Given that there is a .net core version of the Azure Storage SDK (albeit still pre-release), is it feasible to produce a .net core version of the TP?

@isaacabraham I'm happy to have a look into this if you think it would be feasible

**Comment by sergey-tihon** [comment]
Did TPs already work on .net core? I thought that they did not.

**Comment by stewart-r** [comment]
> Did TPs already work on .net core? I thought that they did not.

I saw a similar open 'up for grabs' [issue on FSharp.Data ](https://github.com/fsharp/FSharp.Data/issues/943). When I saw this issue I guess I just assumed TPs were generally do-able on the core clr so thought I'd open this issue up, check if Isaac (or anyone else) had any thoughts then start doing some digging as to how to make it happen.

Between your comment and my own digging it's starting to look like I may have been more than a bit naive with this assumption!

**Comment by isaacabraham** [comment]
I'll be honest with both of you. I've tried my best to keep as far away from .NET Core until it's stable. If you want to have a crack at this, knock yourself out :-) But I'm not planning on doing anything on it for a few weeks / months just yet.

**Comment by tforkmann** [comment]
Currently working on it.
https://github.com/fsprojects/AzureStorageTypeProvider/pull/113

**Comment by isaacabraham** [comment]
This is now fixed Whooo!
