### ISSUE TITLE
Azure Storage connection string via env var

### ISSUE THREAD

**Issue by garrardkitchen** [fsprojects/AzureStorageTypeProvider#81]
### Description

I'm in the throws of creating a solution consisting of several microservices (all F#) running in docker (docker cloud) using your Type Provider, Akka.NET and Nats.io. All working as designed.  Messages flowing through wonderfully from Azure Storage Queue to consumers and worker nodes.  What I'm not sure on at this stage is my strategy on how to handle the connection string to Azure Storage with your TP.  I'm using connectionString permutation in app.config at the moment as seen here:

```
type FromConfig = AzureTypeProvider<connectionStringName = "myConnection", configFileName="sample.config">
```

and having to use a private repo in docker hub.  The pattern that I've seen most using with sensitive info is environment variables (supplied at container runtime).

Is the option of using env vars possible or is this on your road map?  Any advice welcome!

Warmest regards,

Garrard.

**Comment by isaacabraham** [comment]
You have a few options. One is to manually override on every call, although that's probably undesirable. What you might want to look at (although this is somewhat hacky) is rewriting the connection string values right at the start of the application (before the TP initialises) from the environment. I've done something similar for hosting F# apps within the Azure App Service [here](https://github.com/isaacabraham/azure-fsharp-helpers/blob/master/src/configuration.fs).

To be honest I don't know if that's even possible, so if you can try it out and see if that's a viable solution - if not, we can look at adding environment variable support to the TP as well.

**Comment by garrardkitchen** [comment]
Thanks @isaacabraham, I will try this in a short while.

Warmest regards,

Garrard.

**Comment by garrardkitchen** [comment]
Hi @isaacabraham,

Thanks for giving me something to try.

I didn't get anywhere with it unfortunately. I'm now thinking of a hack. I'm going to pass an env var when I run the container in the normal way `-e "foo=baa"`. The `CMD ["",...]` will invoke a script that will (a) insert env var value (connectionString) into app.config and (b) execute mono ./_mymicroservice_.exe.  In theory it should work.  I will just need to make sure that the queue name in dev/test/prod is named the same!

It's not ideal but it should work.  

Warmest regards,

Garrard.

**Comment by isaacabraham** [comment]
OK - perhaps environment variables is something that we should consider in future as well (though I'm not aware of any other TPs etc. supporting them).
